### ISSUE TITLE
인용트윗에 답장 시 문제

### ISSUE THREAD

**Issue by Dalgona** [sokcuri/Kureha#4]
인용트윗이 들어가있는 트윗에 답장을 시도하면 그 트윗을 인용한 사람이 아닌 인용된 트윗을 쓴 사람에게 답장을 쓰게 됩니다.

**Comment by sokcuri** [comment]
흠 심각한문제

**Comment by sokcuri** [comment]
id_str_org 변수가 지역변수가 아니라서 생긴 문제였습니다. 해당 문제를 수정했습니다.
7bbbd45ca51d062c1a7eb33f48584055915c189f
